name: Format Receipt Names

on: 
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Replace with your desired Python version

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the Python script
      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          RECEIPT_DB_ID: ${{ secrets.RECEIPT_DB_ID }}
        run: |
          python ./python/receipt_names.py